name: advices_slip_api
description: An unofficial wrapper around the AdvicesSlip JSON API for providing random advice slips.
version: 1.0.1
repository: https://github.com/exoad/advices_slip_api

environment:
  sdk: ^3.5.3

dependencies:
  http_requests: ^3.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  result_dart: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
